apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api-python
  name: api-python
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: api-python
  template:
    metadata:
      labels:
        io.kompose.service: api-python
    spec:
      containers:
        - image: challenge01api-python:v3
          name: api-python
          ports:
            - containerPort: 5000
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api-python
  name: api-python
spec:
  type: NodePort
  ports:
    - name: service-port-name
      port: 5000
      nodePort: 31112
      protocol: TCP
  selector:
    io.kompose.service: api-python
