version: '3'

services:
  api_python:
    container_name: challenge01-api-python
    image: challenge01api-python:v8
    build: ./API/python
    ports:
      - "5000:5000"

  api_aspnet:
    container_name: challenge01-api-aspnet
    image: challenge01api-aspnet:v1
    build: ./API/aspnet
    ports:
      - "5001:5001"