version: '3'

services:
#  frontend:
#    container_name: challenge01-ui
#    image: challenge01ui:latest
#    build: ./UI
#    ports:
#      - "8080:80"


  api_python:
    container_name: challenge01-api-python
    image: challenge01api-python:v7
    build: ./API
    ports:
      - "5000:5000"