version: '3'

services:
  api_aspnet:
    container_name: challenge01-api-dotnet
    image: 439223726434.dkr.ecr.eu-west-2.amazonaws.com/challenge01api-dotnet:v0.10
    build: ./API/dotnet
    ports:
      - "5001:80"