version: '3'

services:
  frontend:
    container_name: challenge01-ui
    image: challenge01ui:latest
    build: ./UI
    ports:
      - "8080:80"

#  serverless:
#    container_name: challenge01-serverless
#    build: ./Serverless/MilesPerGalonPrediction/app
#    ports:
#      - "3001:8080"