apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\k8s\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 52333
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
