apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: challenge01ui:latest
          imagePullPolicy: IfNotPresent
          name: challenge01-ui
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: service-port-name
      port: 80
      nodePort: 31111
      protocol: TCP
  selector:
    io.kompose.service: frontend
