service: serverless-flask
 
plugins:
  - serverless-python-requirements
 
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  profile: yuriyownaccount
 
functions:
  app:
    handler: app.lambda_handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
